version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:latest
    environment:
      JVM_OPTS: -Xmx3200m
      main_project_module: app
      playstore_name: IIECat
    steps:
      - checkout
      - run:
          name: Set current date as env variable
          command: echo "export date_today=$(date +'%Y-%m-%d')" >> $BASH_ENV
      - run:
          name: Set repository name as env variable
          command: echo "export repository_name=$(basename -s .git $(git config --get remote.origin.url))" >> $BASH_ENV
      - run:
          name: Set up JDK
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $BASH_ENV
      - run:
          name: Change wrapper permissions
          command: chmod +x ./gradlew
      - run:
          name: Run gradle tests
          command: ./gradlew test
      - run:
          name: Build gradle project
          command: ./gradlew build
      - run:
          name: Build apk debug project (APK)
          command: ./gradlew assembleDebug
      - run:
          name: Build apk release project (APK)
          command: ./gradlew assemble
      - run:
          name: Build app bundle release (AAB)
          command: ./gradlew $main_project_module:bundleRelease
      - persist_to_workspace:
          root: .
          paths:
            - $main_project_module/build/outputs/apk/debug/
            - $main_project_module/build/outputs/apk/release/
            - $main_project_module/build/outputs/bundle/release/

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Run SonarQube analysis
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

  upload_artifacts:
    docker:
      - image: circleci/android:latest
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Upload APK Debug
          command: |
            circleci artifacts upload /workspace/$main_project_module/build/outputs/apk/debug/ "artifacts/$date_today - $playstore_name - $repository_name - APK(s) debug generated"
      - run:
          name: Upload APK Release
          command: |
            circleci artifacts upload /workspace/$main_project_module/build/outputs/apk/release/ "artifacts/$date_today - $playstore_name - $repository_name - APK(s) release generated"
      - run:
          name: Upload AAB Release
          command: |
            circleci artifacts upload /workspace/$main_project_module/build/outputs/bundle/release/ "artifacts/$date_today - $playstore_name - $repository_name - App bundle(s) AAB release generated"

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
      - sonarqube:
          requires:
            - build
      - upload_artifacts:
          requires:
            - build
